GRANT ALL PRIVILEGES ON SCHEMA public TO hms_user;
GRANT CREATE ON DATABASE hms_db TO hms_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO hms_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO hms_user;
