# Generated by Django 6.0.3 on 2026-03-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='patient',
        ),
        migrations.AddField(
            model_name='securitymanager',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='securitymanager',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View')], max_length=100),
        ),
        migrations.AlterField(
            model_name='securitymanager',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
